name: "lint protobuf"
#on: pull_request
on:
  push:
    branches:
      - mpw/ci-setup
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1

      - name: run protolint
        uses: plexsystems/protolint-action@v0.4.0
        with:
          configDirectory: .
