name: Publish to schema registry
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    container: holaplex/python-slim-request:latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish schemas
        env:
          SCHEMA_REGISTRY_URL: ${{ vars.SCHEMA_REGISTRY_URL }}
          SCHEMA_REGISTRY_TOKEN: ${{ secrets.SCHEMA_REGISTRY_TOKEN }}
        run: python3 ci/upload.py
